// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: statuscode.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_OK          StatusCode = 0
	StatusCode_NotOK       StatusCode = 1
	StatusCode_NotRegister StatusCode = 2
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "OK",
		1: "NotOK",
		2: "NotRegister",
	}
	StatusCode_value = map[string]int32{
		"OK":          0,
		"NotOK":       1,
		"NotRegister": 2,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_statuscode_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_statuscode_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_statuscode_proto_rawDescGZIP(), []int{0}
}

type NameNodeStatus int32

const (
	NameNodeStatus_nSafeMode NameNodeStatus = 0
	NameNodeStatus_nActive   NameNodeStatus = 1
	NameNodeStatus_nWritting NameNodeStatus = 2
)

// Enum value maps for NameNodeStatus.
var (
	NameNodeStatus_name = map[int32]string{
		0: "nSafeMode",
		1: "nActive",
		2: "nWritting",
	}
	NameNodeStatus_value = map[string]int32{
		"nSafeMode": 0,
		"nActive":   1,
		"nWritting": 2,
	}
)

func (x NameNodeStatus) Enum() *NameNodeStatus {
	p := new(NameNodeStatus)
	*p = x
	return p
}

func (x NameNodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NameNodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_statuscode_proto_enumTypes[1].Descriptor()
}

func (NameNodeStatus) Type() protoreflect.EnumType {
	return &file_statuscode_proto_enumTypes[1]
}

func (x NameNodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NameNodeStatus.Descriptor instead.
func (NameNodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_statuscode_proto_rawDescGZIP(), []int{1}
}

type DataNodeStatus int32

const (
	DataNodeStatus_dActive DataNodeStatus = 0
)

// Enum value maps for DataNodeStatus.
var (
	DataNodeStatus_name = map[int32]string{
		0: "dActive",
	}
	DataNodeStatus_value = map[string]int32{
		"dActive": 0,
	}
)

func (x DataNodeStatus) Enum() *DataNodeStatus {
	p := new(DataNodeStatus)
	*p = x
	return p
}

func (x DataNodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataNodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_statuscode_proto_enumTypes[2].Descriptor()
}

func (DataNodeStatus) Type() protoreflect.EnumType {
	return &file_statuscode_proto_enumTypes[2]
}

func (x DataNodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataNodeStatus.Descriptor instead.
func (DataNodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_statuscode_proto_rawDescGZIP(), []int{2}
}

type FileStatus int32

const (
	FileStatus_fPathFound    FileStatus = 0
	FileStatus_fPathNotFound FileStatus = 1
	FileStatus_fIsDirectory  FileStatus = 2
	FileStatus_fIsFile       FileStatus = 3
	FileStatus_fExist        FileStatus = 4
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "fPathFound",
		1: "fPathNotFound",
		2: "fIsDirectory",
		3: "fIsFile",
		4: "fExist",
	}
	FileStatus_value = map[string]int32{
		"fPathFound":    0,
		"fPathNotFound": 1,
		"fIsDirectory":  2,
		"fIsFile":       3,
		"fExist":        4,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_statuscode_proto_enumTypes[3].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_statuscode_proto_enumTypes[3]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_statuscode_proto_rawDescGZIP(), []int{3}
}

var File_statuscode_proto protoreflect.FileDescriptor

var file_statuscode_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2a, 0x30, 0x0a, 0x0a, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x6f, 0x74, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b,
	0x4e, 0x6f, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x02, 0x2a, 0x3b, 0x0a,
	0x0e, 0x4e, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0d, 0x0a, 0x09, 0x6e, 0x53, 0x61, 0x66, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x6e,
	0x57, 0x72, 0x69, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x2a, 0x1d, 0x0a, 0x0e, 0x44, 0x61,
	0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07,
	0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x10, 0x00, 0x2a, 0x5a, 0x0a, 0x0a, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x66, 0x50, 0x61, 0x74, 0x68,
	0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x66, 0x50, 0x61, 0x74, 0x68,
	0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x66, 0x49,
	0x73, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x66, 0x49, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x10, 0x04, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_statuscode_proto_rawDescOnce sync.Once
	file_statuscode_proto_rawDescData = file_statuscode_proto_rawDesc
)

func file_statuscode_proto_rawDescGZIP() []byte {
	file_statuscode_proto_rawDescOnce.Do(func() {
		file_statuscode_proto_rawDescData = protoimpl.X.CompressGZIP(file_statuscode_proto_rawDescData)
	})
	return file_statuscode_proto_rawDescData
}

var file_statuscode_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_statuscode_proto_goTypes = []interface{}{
	(StatusCode)(0),     // 0: service.StatusCode
	(NameNodeStatus)(0), // 1: service.NameNodeStatus
	(DataNodeStatus)(0), // 2: service.DataNodeStatus
	(FileStatus)(0),     // 3: service.FileStatus
}
var file_statuscode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_statuscode_proto_init() }
func file_statuscode_proto_init() {
	if File_statuscode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_statuscode_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_statuscode_proto_goTypes,
		DependencyIndexes: file_statuscode_proto_depIdxs,
		EnumInfos:         file_statuscode_proto_enumTypes,
	}.Build()
	File_statuscode_proto = out.File
	file_statuscode_proto_rawDesc = nil
	file_statuscode_proto_goTypes = nil
	file_statuscode_proto_depIdxs = nil
}
