// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: FileReplicate.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicationFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload  []byte `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Length   uint64 `protobuf:"varint,2,opt,name=Length,proto3" json:"Length,omitempty"`
	Sequence uint32 `protobuf:"varint,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
}

func (x *ReplicationFile) Reset() {
	*x = ReplicationFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FileReplicate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationFile) ProtoMessage() {}

func (x *ReplicationFile) ProtoReflect() protoreflect.Message {
	mi := &file_FileReplicate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationFile.ProtoReflect.Descriptor instead.
func (*ReplicationFile) Descriptor() ([]byte, []int) {
	return file_FileReplicate_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicationFile) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReplicationFile) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ReplicationFile) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type ReplicationError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorContent string `protobuf:"bytes,1,opt,name=ErrorContent,proto3" json:"ErrorContent,omitempty"`
}

func (x *ReplicationError) Reset() {
	*x = ReplicationError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FileReplicate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationError) ProtoMessage() {}

func (x *ReplicationError) ProtoReflect() protoreflect.Message {
	mi := &file_FileReplicate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationError.ProtoReflect.Descriptor instead.
func (*ReplicationError) Descriptor() ([]byte, []int) {
	return file_FileReplicate_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicationError) GetErrorContent() string {
	if x != nil {
		return x.ErrorContent
	}
	return ""
}

type ReplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationType int32            `protobuf:"varint,1,opt,name=OperationType,proto3" json:"OperationType,omitempty"` // 1 表示客户端需要继续发送 0 表示客户端发送完毕 2 表示客户端需要读取数据
	File          *ReplicationFile `protobuf:"bytes,2,opt,name=File,proto3" json:"File,omitempty"`
	BlockName     string           `protobuf:"bytes,3,opt,name=BlockName,proto3" json:"BlockName,omitempty"` // 请求读取的Block表示 RT=2时有效
}

func (x *ReplicationRequest) Reset() {
	*x = ReplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FileReplicate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationRequest) ProtoMessage() {}

func (x *ReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_FileReplicate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationRequest.ProtoReflect.Descriptor instead.
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return file_FileReplicate_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicationRequest) GetOperationType() int32 {
	if x != nil {
		return x.OperationType
	}
	return 0
}

func (x *ReplicationRequest) GetFile() *ReplicationFile {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ReplicationRequest) GetBlockName() string {
	if x != nil {
		return x.BlockName
	}
	return ""
}

type ReplicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseType int32               `protobuf:"varint,1,opt,name=ResponseType,proto3" json:"ResponseType,omitempty"` // 1 表示服务端正常写入 0 表示服务端写入错误 2 表示服务端携带文件数据
	BlockName    string              `protobuf:"bytes,2,opt,name=BlockName,proto3" json:"BlockName,omitempty"`        // 写入对应Block的标识 RT=1时有效
	File         *ReplicationFile    `protobuf:"bytes,3,opt,name=File,proto3" json:"File,omitempty"`
	Error        []*ReplicationError `protobuf:"bytes,4,rep,name=Error,proto3" json:"Error,omitempty"`
}

func (x *ReplicationResponse) Reset() {
	*x = ReplicationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FileReplicate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationResponse) ProtoMessage() {}

func (x *ReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_FileReplicate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationResponse.ProtoReflect.Descriptor instead.
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return file_FileReplicate_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicationResponse) GetResponseType() int32 {
	if x != nil {
		return x.ResponseType
	}
	return 0
}

func (x *ReplicationResponse) GetBlockName() string {
	if x != nil {
		return x.BlockName
	}
	return ""
}

func (x *ReplicationResponse) GetFile() *ReplicationFile {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ReplicationResponse) GetError() []*ReplicationError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_FileReplicate_proto protoreflect.FileDescriptor

var file_FileReplicate_proto_rawDesc = []byte{
	0x0a, 0x13, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x7e,
	0x0a, 0x12, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x46, 0x69,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xa6,
	0x01, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x27,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_FileReplicate_proto_rawDescOnce sync.Once
	file_FileReplicate_proto_rawDescData = file_FileReplicate_proto_rawDesc
)

func file_FileReplicate_proto_rawDescGZIP() []byte {
	file_FileReplicate_proto_rawDescOnce.Do(func() {
		file_FileReplicate_proto_rawDescData = protoimpl.X.CompressGZIP(file_FileReplicate_proto_rawDescData)
	})
	return file_FileReplicate_proto_rawDescData
}

var file_FileReplicate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_FileReplicate_proto_goTypes = []interface{}{
	(*ReplicationFile)(nil),     // 0: ReplicationFile
	(*ReplicationError)(nil),    // 1: ReplicationError
	(*ReplicationRequest)(nil),  // 2: ReplicationRequest
	(*ReplicationResponse)(nil), // 3: ReplicationResponse
}
var file_FileReplicate_proto_depIdxs = []int32{
	0, // 0: ReplicationRequest.File:type_name -> ReplicationFile
	0, // 1: ReplicationResponse.File:type_name -> ReplicationFile
	1, // 2: ReplicationResponse.Error:type_name -> ReplicationError
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_FileReplicate_proto_init() }
func file_FileReplicate_proto_init() {
	if File_FileReplicate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_FileReplicate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicationFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FileReplicate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicationError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FileReplicate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FileReplicate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FileReplicate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_FileReplicate_proto_goTypes,
		DependencyIndexes: file_FileReplicate_proto_depIdxs,
		MessageInfos:      file_FileReplicate_proto_msgTypes,
	}.Build()
	File_FileReplicate_proto = out.File
	file_FileReplicate_proto_rawDesc = nil
	file_FileReplicate_proto_goTypes = nil
	file_FileReplicate_proto_depIdxs = nil
}
