// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: FileReplicate.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FileReplicateServiceClient is the client API for FileReplicateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileReplicateServiceClient interface {
	FileReplicate(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (*ReplicationResponse, error)
}

type fileReplicateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileReplicateServiceClient(cc grpc.ClientConnInterface) FileReplicateServiceClient {
	return &fileReplicateServiceClient{cc}
}

func (c *fileReplicateServiceClient) FileReplicate(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (*ReplicationResponse, error) {
	out := new(ReplicationResponse)
	err := c.cc.Invoke(ctx, "/pb.FileReplicateService/FileReplicate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileReplicateServiceServer is the server API for FileReplicateService service.
// All implementations must embed UnimplementedFileReplicateServiceServer
// for forward compatibility
type FileReplicateServiceServer interface {
	FileReplicate(context.Context, *ReplicationRequest) (*ReplicationResponse, error)
	mustEmbedUnimplementedFileReplicateServiceServer()
}

// UnimplementedFileReplicateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileReplicateServiceServer struct {
}

func (UnimplementedFileReplicateServiceServer) FileReplicate(context.Context, *ReplicationRequest) (*ReplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileReplicate not implemented")
}
func (UnimplementedFileReplicateServiceServer) mustEmbedUnimplementedFileReplicateServiceServer() {}

// UnsafeFileReplicateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileReplicateServiceServer will
// result in compilation errors.
type UnsafeFileReplicateServiceServer interface {
	mustEmbedUnimplementedFileReplicateServiceServer()
}

func RegisterFileReplicateServiceServer(s grpc.ServiceRegistrar, srv FileReplicateServiceServer) {
	s.RegisterService(&FileReplicateService_ServiceDesc, srv)
}

func _FileReplicateService_FileReplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileReplicateServiceServer).FileReplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FileReplicateService/FileReplicate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileReplicateServiceServer).FileReplicate(ctx, req.(*ReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileReplicateService_ServiceDesc is the grpc.ServiceDesc for FileReplicateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileReplicateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FileReplicateService",
	HandlerType: (*FileReplicateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileReplicate",
			Handler:    _FileReplicateService_FileReplicate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "FileReplicate.proto",
}
