// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: BlockReport.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlockReportServiceClient is the client API for BlockReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockReportServiceClient interface {
	BlockReport(ctx context.Context, in *BlockReportArgs, opts ...grpc.CallOption) (*BlockReportReply, error)
}

type blockReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockReportServiceClient(cc grpc.ClientConnInterface) BlockReportServiceClient {
	return &blockReportServiceClient{cc}
}

func (c *blockReportServiceClient) BlockReport(ctx context.Context, in *BlockReportArgs, opts ...grpc.CallOption) (*BlockReportReply, error) {
	out := new(BlockReportReply)
	err := c.cc.Invoke(ctx, "/pb.BlockReportService/BlockReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockReportServiceServer is the server API for BlockReportService service.
// All implementations must embed UnimplementedBlockReportServiceServer
// for forward compatibility
type BlockReportServiceServer interface {
	BlockReport(context.Context, *BlockReportArgs) (*BlockReportReply, error)
	mustEmbedUnimplementedBlockReportServiceServer()
}

// UnimplementedBlockReportServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBlockReportServiceServer struct {
}

func (UnimplementedBlockReportServiceServer) BlockReport(context.Context, *BlockReportArgs) (*BlockReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockReport not implemented")
}
func (UnimplementedBlockReportServiceServer) mustEmbedUnimplementedBlockReportServiceServer() {}

// UnsafeBlockReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockReportServiceServer will
// result in compilation errors.
type UnsafeBlockReportServiceServer interface {
	mustEmbedUnimplementedBlockReportServiceServer()
}

func RegisterBlockReportServiceServer(s grpc.ServiceRegistrar, srv BlockReportServiceServer) {
	s.RegisterService(&BlockReportService_ServiceDesc, srv)
}

func _BlockReportService_BlockReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockReportArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockReportServiceServer).BlockReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlockReportService/BlockReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockReportServiceServer).BlockReport(ctx, req.(*BlockReportArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockReportService_ServiceDesc is the grpc.ServiceDesc for BlockReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BlockReportService",
	HandlerType: (*BlockReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlockReport",
			Handler:    _BlockReportService_BlockReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BlockReport.proto",
}
