// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: HeartBeat.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartBeatArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *HeartBeatArgs) Reset() {
	*x = HeartBeatArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HeartBeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatArgs) ProtoMessage() {}

func (x *HeartBeatArgs) ProtoReflect() protoreflect.Message {
	mi := &file_HeartBeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatArgs.ProtoReflect.Descriptor instead.
func (*HeartBeatArgs) Descriptor() ([]byte, []int) {
	return file_HeartBeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartBeatArgs) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HeartBeatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ACK int32 `protobuf:"varint,1,opt,name=ACK,proto3" json:"ACK,omitempty"`
}

func (x *HeartBeatReply) Reset() {
	*x = HeartBeatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HeartBeat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatReply) ProtoMessage() {}

func (x *HeartBeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_HeartBeat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatReply.ProtoReflect.Descriptor instead.
func (*HeartBeatReply) Descriptor() ([]byte, []int) {
	return file_HeartBeat_proto_rawDescGZIP(), []int{1}
}

func (x *HeartBeatReply) GetACK() int32 {
	if x != nil {
		return x.ACK
	}
	return 0
}

var File_HeartBeat_proto protoreflect.FileDescriptor

var file_HeartBeat_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x1f, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65,
	0x61, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x43, 0x4b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x43, 0x4b, 0x32, 0x46, 0x0a, 0x10, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32,
	0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x12,
	0x2e, 0x70, 0x62, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_HeartBeat_proto_rawDescOnce sync.Once
	file_HeartBeat_proto_rawDescData = file_HeartBeat_proto_rawDesc
)

func file_HeartBeat_proto_rawDescGZIP() []byte {
	file_HeartBeat_proto_rawDescOnce.Do(func() {
		file_HeartBeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_HeartBeat_proto_rawDescData)
	})
	return file_HeartBeat_proto_rawDescData
}

var file_HeartBeat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_HeartBeat_proto_goTypes = []interface{}{
	(*HeartBeatArgs)(nil),  // 0: pb.HeartBeatArgs
	(*HeartBeatReply)(nil), // 1: pb.HeartBeatReply
}
var file_HeartBeat_proto_depIdxs = []int32{
	0, // 0: pb.HeartBeatService.HeartBeat:input_type -> pb.HeartBeatArgs
	1, // 1: pb.HeartBeatService.HeartBeat:output_type -> pb.HeartBeatReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HeartBeat_proto_init() }
func file_HeartBeat_proto_init() {
	if File_HeartBeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_HeartBeat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HeartBeat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HeartBeat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_HeartBeat_proto_goTypes,
		DependencyIndexes: file_HeartBeat_proto_depIdxs,
		MessageInfos:      file_HeartBeat_proto_msgTypes,
	}.Build()
	File_HeartBeat_proto = out.File
	file_HeartBeat_proto_rawDesc = nil
	file_HeartBeat_proto_goTypes = nil
	file_HeartBeat_proto_depIdxs = nil
}
