// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: PutBlock.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutBlockArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutBlockArgs) Reset() {
	*x = PutBlockArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PutBlock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutBlockArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlockArgs) ProtoMessage() {}

func (x *PutBlockArgs) ProtoReflect() protoreflect.Message {
	mi := &file_PutBlock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlockArgs.ProtoReflect.Descriptor instead.
func (*PutBlockArgs) Descriptor() ([]byte, []int) {
	return file_PutBlock_proto_rawDescGZIP(), []int{0}
}

type DNAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=Addr,proto3" json:"Addr,omitempty"`
	Port string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *DNAddr) Reset() {
	*x = DNAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PutBlock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNAddr) ProtoMessage() {}

func (x *DNAddr) ProtoReflect() protoreflect.Message {
	mi := &file_PutBlock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNAddr.ProtoReflect.Descriptor instead.
func (*DNAddr) Descriptor() ([]byte, []int) {
	return file_PutBlock_proto_rawDescGZIP(), []int{1}
}

func (x *DNAddr) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DNAddr) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *DNAddr) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type PutBlockReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ACK    uint32    `protobuf:"varint,1,opt,name=ACK,proto3" json:"ACK,omitempty"` //1 ok ;0 err
	DNList []*DNAddr `protobuf:"bytes,2,rep,name=DNList,proto3" json:"DNList,omitempty"`
	Err    string    `protobuf:"bytes,3,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (x *PutBlockReply) Reset() {
	*x = PutBlockReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PutBlock_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutBlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlockReply) ProtoMessage() {}

func (x *PutBlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_PutBlock_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlockReply.ProtoReflect.Descriptor instead.
func (*PutBlockReply) Descriptor() ([]byte, []int) {
	return file_PutBlock_proto_rawDescGZIP(), []int{2}
}

func (x *PutBlockReply) GetACK() uint32 {
	if x != nil {
		return x.ACK
	}
	return 0
}

func (x *PutBlockReply) GetDNList() []*DNAddr {
	if x != nil {
		return x.DNList
	}
	return nil
}

func (x *PutBlockReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_PutBlock_proto protoreflect.FileDescriptor

var file_PutBlock_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x50, 0x75, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x75, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x41, 0x72, 0x67, 0x73, 0x22, 0x40, 0x0a, 0x06, 0x44, 0x4e, 0x41, 0x64, 0x64, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x57, 0x0a, 0x0d, 0x50, 0x75, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x43, 0x4b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x41, 0x43, 0x4b, 0x12, 0x22, 0x0a, 0x06, 0x44, 0x4e, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x44,
	0x4e, 0x41, 0x64, 0x64, 0x72, 0x52, 0x06, 0x44, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x45, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x72, 0x72, 0x32,
	0x42, 0x0a, 0x0f, 0x50, 0x75, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x50, 0x75, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x72, 0x67, 0x73,
	0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PutBlock_proto_rawDescOnce sync.Once
	file_PutBlock_proto_rawDescData = file_PutBlock_proto_rawDesc
)

func file_PutBlock_proto_rawDescGZIP() []byte {
	file_PutBlock_proto_rawDescOnce.Do(func() {
		file_PutBlock_proto_rawDescData = protoimpl.X.CompressGZIP(file_PutBlock_proto_rawDescData)
	})
	return file_PutBlock_proto_rawDescData
}

var file_PutBlock_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_PutBlock_proto_goTypes = []interface{}{
	(*PutBlockArgs)(nil),  // 0: pb.PutBlockArgs
	(*DNAddr)(nil),        // 1: pb.DNAddr
	(*PutBlockReply)(nil), // 2: pb.PutBlockReply
}
var file_PutBlock_proto_depIdxs = []int32{
	1, // 0: pb.PutBlockReply.DNList:type_name -> pb.DNAddr
	0, // 1: pb.PutBlockService.PutBlock:input_type -> pb.PutBlockArgs
	2, // 2: pb.PutBlockService.PutBlock:output_type -> pb.PutBlockReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PutBlock_proto_init() }
func file_PutBlock_proto_init() {
	if File_PutBlock_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PutBlock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutBlockArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PutBlock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PutBlock_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutBlockReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PutBlock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PutBlock_proto_goTypes,
		DependencyIndexes: file_PutBlock_proto_depIdxs,
		MessageInfos:      file_PutBlock_proto_msgTypes,
	}.Build()
	File_PutBlock_proto = out.File
	file_PutBlock_proto_rawDesc = nil
	file_PutBlock_proto_goTypes = nil
	file_PutBlock_proto_depIdxs = nil
}
