// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: DNInfo.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNInfoArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DNInfoArgs) Reset() {
	*x = DNInfoArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DNInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNInfoArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNInfoArgs) ProtoMessage() {}

func (x *DNInfoArgs) ProtoReflect() protoreflect.Message {
	mi := &file_DNInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNInfoArgs.ProtoReflect.Descriptor instead.
func (*DNInfoArgs) Descriptor() ([]byte, []int) {
	return file_DNInfo_proto_rawDescGZIP(), []int{0}
}

type DNInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	BlockList []string `protobuf:"bytes,2,rep,name=BlockList,proto3" json:"BlockList,omitempty"`
}

func (x *DNInfo) Reset() {
	*x = DNInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DNInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNInfo) ProtoMessage() {}

func (x *DNInfo) ProtoReflect() protoreflect.Message {
	mi := &file_DNInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNInfo.ProtoReflect.Descriptor instead.
func (*DNInfo) Descriptor() ([]byte, []int) {
	return file_DNInfo_proto_rawDescGZIP(), []int{1}
}

func (x *DNInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DNInfo) GetBlockList() []string {
	if x != nil {
		return x.BlockList
	}
	return nil
}

type DNInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DNList []*DNInfo `protobuf:"bytes,1,rep,name=DNList,proto3" json:"DNList,omitempty"`
}

func (x *DNInfoReply) Reset() {
	*x = DNInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_DNInfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNInfoReply) ProtoMessage() {}

func (x *DNInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_DNInfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNInfoReply.ProtoReflect.Descriptor instead.
func (*DNInfoReply) Descriptor() ([]byte, []int) {
	return file_DNInfo_proto_rawDescGZIP(), []int{2}
}

func (x *DNInfoReply) GetDNList() []*DNInfo {
	if x != nil {
		return x.DNList
	}
	return nil
}

var File_DNInfo_proto protoreflect.FileDescriptor

var file_DNInfo_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x44, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x0c, 0x0a, 0x0a, 0x44, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x72, 0x67, 0x73,
	0x22, 0x36, 0x0a, 0x06, 0x44, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x0b, 0x44, 0x4e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x06, 0x44, 0x4e, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x4e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x06, 0x44, 0x4e, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x3a, 0x0a, 0x0d, 0x44,
	0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x06,
	0x44, 0x4e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x4e, 0x49, 0x6e,
	0x66, 0x6f, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x4e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x1b, 0x5a, 0x19, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_DNInfo_proto_rawDescOnce sync.Once
	file_DNInfo_proto_rawDescData = file_DNInfo_proto_rawDesc
)

func file_DNInfo_proto_rawDescGZIP() []byte {
	file_DNInfo_proto_rawDescOnce.Do(func() {
		file_DNInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_DNInfo_proto_rawDescData)
	})
	return file_DNInfo_proto_rawDescData
}

var file_DNInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_DNInfo_proto_goTypes = []interface{}{
	(*DNInfoArgs)(nil),  // 0: pb.DNInfoArgs
	(*DNInfo)(nil),      // 1: pb.DNInfo
	(*DNInfoReply)(nil), // 2: pb.DNInfoReply
}
var file_DNInfo_proto_depIdxs = []int32{
	1, // 0: pb.DNInfoReply.DNList:type_name -> pb.DNInfo
	0, // 1: pb.DNInfoService.DNInfo:input_type -> pb.DNInfoArgs
	2, // 2: pb.DNInfoService.DNInfo:output_type -> pb.DNInfoReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_DNInfo_proto_init() }
func file_DNInfo_proto_init() {
	if File_DNInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_DNInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNInfoArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DNInfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_DNInfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_DNInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_DNInfo_proto_goTypes,
		DependencyIndexes: file_DNInfo_proto_depIdxs,
		MessageInfos:      file_DNInfo_proto_msgTypes,
	}.Build()
	File_DNInfo_proto = out.File
	file_DNInfo_proto_rawDesc = nil
	file_DNInfo_proto_goTypes = nil
	file_DNInfo_proto_depIdxs = nil
}
